# -*- coding: utf-8 -*-
"""Our-Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZfGLtPmTzZ7oLnfjNdewYGZDD93Wwb4
"""

!pip install package_name  # For Python packages
!apt-get install package_name -y  # For system packages (Linux)
!pip install --upgrade transformers
import transformers
print(transformers.__version__)
from transformers import AutoModel
print(dir(AutoModel))
from transformers import AutoModelForSemanticSegmentation
from transformers import SwinModel, SwinForImageClassification, ViTForImageClassification, ViTFeatureExtractor, AutoModelForSemanticSegmentation

import torch
import torchvision.transforms as transforms
import torch.nn as nn
import torch.optim as optim
import torchvision.models as models
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
from transformers import SwinModel, SwinForImageClassification, ViTForImageClassification, ViTFeatureExtractor, AutoModelForSemanticSegmentation
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
import os

"""
# Mount Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""# Set dataset path (update this based on your dataset location)"""

data_dir = '/content/drive/MyDrive/Dataset/Test_Train'

"""# Define image transformations"""

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

"""# Load dataset"""

dataset = ImageFolder(root=data_dir, transform=transform)
data_loader = DataLoader(dataset, batch_size=16, shuffle=True)

"""# Load Swin Transformer for Tumor Segmentation"""

from transformers import AutoModelForSemanticSegmentation

segmentation_model = AutoModelForSemanticSegmentation.from_pretrained("nvidia/segformer-b0-finetuned-ade-512-512")
segmentation_model.eval()

# Load a segmentation model (UperNet with Swin Backbone)
swin_model = AutoModelForSemanticSegmentation.from_pretrained("openmmlab/upernet-swin-tiny")
swin_model.eval()

"""# Load Vision Transformer for Tumor Detection, Classification, and Grading"""

vit_model_detection = ViTForImageClassification.from_pretrained("google/vit-base-patch16-224")
vit_model_classification = ViTForImageClassification.from_pretrained("google/vit-base-patch16-224")
vit_model_grading = ViTForImageClassification.from_pretrained("google/vit-base-patch16-224")

vit_model_detection.eval()
vit_model_classification.eval()
vit_model_grading.eval()

"""# Define a function for segmentation using Swin Transformer"""

def segment_tumor(image_path):
    image = Image.open(image_path).convert("RGB")
    transform_seg = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor()
    ])
    image = transform_seg(image).unsqueeze(0)

    with torch.no_grad():
        output = swin_model(image).logits

    segmentation_map = torch.argmax(output, dim=1).squeeze().cpu().numpy()
    plt.imshow(segmentation_map, cmap='gray')
    plt.title("Tumor Segmentation")
    plt.show()
    return segmentation_map

"""# Define a function for tumor detection"""

def detect_tumor(image_path):
    image = Image.open(image_path).convert("RGB")
    transform_cls = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
    ])
    image = transform_cls(image).unsqueeze(0)

    with torch.no_grad():
        output = vit_model_detection(image).logits

    predicted_class = torch.argmax(output, dim=1).item()
    classes = ["No Tumor", "Tumor Present"]  # Binary classification

    return classes[predicted_class]

"""# Define a function for tumor classification"""

def classify_tumor(image_path):
    image = Image.open(image_path).convert("RGB")
    transform_cls = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
    ])
    image = transform_cls(image).unsqueeze(0)

    with torch.no_grad():
        output = vit_model_classification(image).logits

    predicted_class = torch.argmax(output, dim=1).item()
    classes = dataset.classes  # Get class names from dataset

    return classes[predicted_class]

"""# Define a function for tumor grading (Low/High Grade)"""

def grade_tumor(image_path):
    image = Image.open(image_path).convert("RGB")
    transform_cls = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
    ])
    image = transform_cls(image).unsqueeze(0)

    with torch.no_grad():
        output = vit_model_grading(image).logits

    predicted_class = torch.argmax(output, dim=1).item()
    classes = ["Low Grade", "High Grade"]  # Binary classification for tumor grading

    return classes[predicted_class]

def classify_tumor(image_path):
    from transformers import ViTForImageClassification

    # Load a classification model (adjust for your dataset)
    classification_model = ViTForImageClassification.from_pretrained("google/vit-base-patch16-224")
    classification_model.eval()

    image = Image.open(image_path).convert("RGB")

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
    ])
    image = transform(image).unsqueeze(0)

    with torch.no_grad():
        outputs = classification_model(image)
        predicted_class = torch.argmax(outputs.logits, dim=1).item()

    # Ensure correct class labels (adjust based on your model training)
    classes = ["Glioma", "Meningioma", "Pituitary", "No Tumor"]

    if predicted_class < 0 or predicted_class >= len(classes):
        return "Unknown Class (Model Output Invalid)"

    return classes[predicted_class]

def grade_tumor(image_path):
    from transformers import ViTForImageClassification

    grading_model = ViTForImageClassification.from_pretrained("google/vit-base-patch16-224")
    grading_model.eval()

    image = Image.open(image_path).convert("RGB")

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
    ])
    image = transform(image).unsqueeze(0)

    with torch.no_grad():
        outputs = grading_model(image)
        predicted_class = torch.argmax(outputs.logits, dim=1).item()

    # Define tumor grading levels
    grades = ["Low Grade", "High Grade"]

    if predicted_class < 0 or predicted_class >= len(grades):
        return "Unknown Grade (Model Output Invalid)"

    return grades[predicted_class]

def detect_tumor(image_path):
    from transformers import ViTForImageClassification

    detection_model = ViTForImageClassification.from_pretrained("google/vit-base-patch16-224")
    detection_model.eval()

    image = Image.open(image_path).convert("RGB")

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
    ])
    image = transform(image).unsqueeze(0)

    with torch.no_grad():
        outputs = detection_model(image)
        predicted_class = torch.argmax(outputs.logits, dim=1).item()

    # Binary classification: Tumor vs No Tumor
    classes = ["No Tumor", "Tumor Present"]

    if predicted_class < 0 or predicted_class >= len(classes):
        return "Unknown Detection (Model Output Invalid)"

    return classes[predicted_class]

"""# Example Usage/Run the functions"""

image_path = "/content/drive/MyDrive/Dataset/Testing/no_tumor/image(95).jpg"

segmentation_result = segment_tumor(image_path)
detection_result = detect_tumor(image_path)
classification_result = classify_tumor(image_path)
grading_result = grade_tumor(image_path)

print(f"Tumor Detection: {detection_result}")
print(f"Tumor Classification: {classification_result}")
print(f"Tumor Grading: {grading_result}")

